AllCops:
  TargetRubyVersion: 2.7.0

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/ModuleLength:
  Max: 155

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 13

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassVars:
  Enabled: false